city_research_task:
  description: >
    Research and analyze {city_name} and its business ecosystem in {industry_name} industry:
        1. Get city summary and key information
        2. Find organizations in the specified industry
        3. Analyze business relationships and economic indicators
  expected_output: >
    Basic statistics about the companies in the given city and industry as well as top performers
  agent: data_researcher

news_analysis_task:
  description: >
    Analyze recent news about the companies provided by the city researcher
  expected_output: >
    Summarization of the latest news for the company and how it might affect the market
  agent: news_analyst

report_writing_task:
  description: >
    Create a detailed markdown report about the
    results you got from city research and news analysis tasks.
    Do not include any information that isn't provided
  expected_output: >
    Markdown summary report with key insights and recommendations.
  agent: report_writer